### ISSUE TITLE
Irregular exception : Negative leftover value: -0.000000

### ISSUE THREAD

**Issue by bbeaulant** [fontanf/packingsolver#80]
Hello,

With the following [test_input.json](https://github.com/user-attachments/files/16740215/test_input.json), the solver throws the following exception : 

`irregular::Solution::add_item. Negative leftover value: -0.000000.`

Regards

**Comment by fontanf** [comment]
Hi

Thank you for reporting.

The issue seems to have been fixed in the current version. So I'll close the issue

**Comment by bbeaulant** [comment]
On my computer, with the last dev branch, the problem persists with the given input.

Here is a debugger screenshot of `leftover_value_`

![Capture d’écran 2024-08-31 à 08 10 12](https://github.com/user-attachments/assets/469c0c8f-5bc3-48b8-adcf-83c6477a7031)

**Comment by fontanf** [comment]
Are you sure it's the input above? To have a leftover value of 0, the last bin needs to be completely full, which doesn't seem to be the case for this input

**Comment by bbeaulant** [comment]
Yes, I'm sure.

Here is the solution written just before throwing the exception :

```json
{
    "bins": [
        {
            "copies": 1,
            "id": 0,
            "items": [
                {
                    "angle": 0.0,
                    "id": 0,
                    "item_shapes": [
                        {
                            "shape": [
                                {
                                    "type": "LineSegment",
                                    "xe": 59.055118109999995,
                                    "xs": 74.14643419,
                                    "ye": 3.93700787,
                                    "ys": 3.93700787
                                },
                                {
                                    "type": "LineSegment",
                                    "xe": 59.055118109999995,
                                    "xs": 59.055118109999995,
                                    "ye": 0.0,
                                    "ys": 3.93700787
                                },
                                {
                                    "type": "LineSegment",
                                    "xe": 78.74015748,
                                    "xs": 59.055118109999995,
                                    "ye": 0.0,
                                    "ys": 0.0
                                },
                                {
                                    "type": "LineSegment",
                                    "xe": 74.14643419,
                                    "xs": 78.74015748,
                                    "ye": 3.93700787,
                                    "ys": 0.0
                                }
                            ]
                        }
                    ],
                    "mirror": false,
                    "x": 59.055118109999995,
                    "y": 0.0
                }
            ],
            "shape": [
                {
                    "type": "LineSegment",
                    "xe": 78.74015748,
                    "xs": 0.0,
                    "ye": 0.0,
                    "ys": 0.0
                },
                {
                    "type": "LineSegment",
                    "xe": 78.74015748,
                    "xs": 78.74015748,
                    "ye": 3.93700787,
                    "ys": 0.0
                },
                {
                    "type": "LineSegment",
                    "xe": 0.0,
                    "xs": 78.74015748,
                    "ye": 3.93700787,
                    "ys": 3.93700787
                },
                {
                    "type": "LineSegment",
                    "xe": 0.0,
                    "xs": 0.0,
                    "ye": 0.0,
                    "ys": 3.93700787
                }
            ]
        }
    ]
}

```

**Comment by fontanf** [comment]
I still can't reproduce. I disabled the check
